import type { ThemeConfig } from 'antd';

const theme: ThemeConfig = {
  token: {
    // fontFamily: `OperatorMono, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'`,
    colorPrimary: '#2b5fdc',
    colorError: '#e62c3b',
    colorInfo: '#2b5fdc',
    colorLink: '#2b5fdc',
    colorSuccess: '#11bb43',
    colorTextBase: '#2A303B',
    colorWarning: '#fa6a0a',
    colorErrorActive: '#c01b2f',
    colorErrorBg: '#fff6f5',
    colorErrorBgHover: '#eb4f57',
    colorErrorHover: '#eb4f57',
    colorErrorText: '#e62c3b',
    colorErrorTextActive: '#c01b2f',
    colorErrorTextHover: '#eb4f57',
    colorInfoActive: '#1b45b8',
    colorInfoBg: '#f5f8ff',
    colorInfoBgHover: '#4d7fe3',
    colorInfoHover: '#4d7fe3',
    colorInfoText: '#2b5fdc',
    colorInfoTextActive: '#1b45b8',
    colorInfoTextHover: '#4d7fe3',
    colorLinkActive: '#1b45b8',
    colorLinkHover: '#4d7fe3',
    colorPrimaryActive: '#1b45b8',
    colorPrimaryBg: '#f5f8ff',
    colorPrimaryBgHover: '#4d7fe3',
    colorPrimaryHover: '#4d7fe3',
    colorPrimaryText: '#2b5fdc',
    colorPrimaryTextActive: '#1b45b8',
    colorPrimaryTextHover: '#4d7fe3',
    colorSuccessActive: '#0b9f3c',
    colorSuccessBg: '#f5fff5',
    colorSuccessBgHover: '#33c95b',
    colorSuccessHover: '#33c95b',
    colorSuccessText: '#11bb43',
    colorSuccessTextActive: '#0b9f3c',
    colorSuccessTextHover: '#33c95b',
    colorWarningActive: '#cf5006',
    colorWarningBg: '#fff5e8',
    colorWarningBgHover: '#fb8b36',
    colorWarningHover: '#fb8b36',
    colorWarningText: '#fa6a0a',
    colorWarningTextActive: '#cf5006',
    colorWarningTextHover: '#fb8b36',
    colorErrorOutline: '#c01b2f',
    colorHighlight: '#fa6a0a',
  },
};

export default theme;
